version: "3"
services:
  db:
    container_name: jeinkins_db
    image: mysql:5.6
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=9ZxPyx4i8ooBrlN6
    volumes:
      - db_data:/var/lib/mysql
      - /jenkins-data/workspace/${JOB_NAME}/sql:/docker-entrypoint-initdb.d
    command: 
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  php:
    container_name: jenkins_php
    image: php:build_${BUILD_NUMBER}
    build:
      context: ./php
    networks:
      - db
      - front
    volumes:    
      - "/jenkins-data/workspace/${JOB_NAME}/app:/var/www/html"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=9ZxPyx4i8ooBrlN6
      - APP_VERSION=build_${BUILD_NUMBER}
    depends_on:
      - db

  nginx:
    container_name: jenkins_nginx
    image: nginx:1-alpine
    volumes:
      - "/jenkins-data/workspace/${JOB_NAME}/app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - front
    ports:
      - 80:80
    environment:
      - APP_VERSION=build_${BUILD_NUMBER}
    depends_on:
      - jenkins_php

networks:
  db:
  front:

volumes: 
  db_data: