version: "3"
services:
  db:
    container_name: db
    image: mysql:5.6
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=9ZxPyx4i8ooBrlN6
    volumes:
      - db_data:/var/lib/mysql
    command: 
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  php:
    container_name: php
    image: php:build_${BUILD_NUMBER}
    build:
      context: ./php
    ports:
      - 80:80
    networks:
      - db
      - front
    volumes:    
      - "./app:/var/www/html"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=9ZxPyx4i8ooBrlN6
    depends_on:
      - db

  # nginx:
  #   container_name: frontend-prod
  #   image: front_prod:build_${BUILD_NUMBER}
  #   build:
  #       context: .
  #       args:
  #         - WAR_FILE=frontend/target/tasks.war
  #         - CONTEXT=tasks
  #   networks:
  #     - prod_net_front
  #   ports:
  #     - 9999:8080
  #   environment:
  #     - BACKEND_HOST=backend
  #     - BACKEND_PORT=8080
  #     - APP_VERSION=build_${BUILD_NUMBER}
  #   #depends_on:
  #   #  - backend

networks:
  db:
  front:

volumes:
  db_data:  